/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'us-east-1',
	aws_cognito_identity_pool_id: 'us-east-1:11341a48-8ecc-4301-bdb9-9ffb017e841d',
	aws_cognito_region: 'us-east-1',
	aws_user_pools_id: 'us-east-1_oYnXmztBc',
	aws_user_pools_web_client_id: '28qq3t4omnh55crik2mhf1ahj2',
	oauth: {
		domain: 'jtry3c98bce33-c98bce33-devjim.auth.us-east-1.amazoncognito.com',
		scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
		redirectSignIn: 'https://main.d1clupy9fa29m0.amplifyapp.com/',
		redirectSignOut: 'https://main.d1clupy9fa29m0.amplifyapp.com/',
		responseType: 'code',
	},
	federationTarget: 'COGNITO_USER_POOLS',
	aws_cognito_username_attributes: ['EMAIL'],
	aws_cognito_social_providers: ['FACEBOOK', 'GOOGLE'],
	aws_cognito_signup_attributes: ['EMAIL', 'FAMILY_NAME', 'NAME'],
	aws_cognito_mfa_configuration: 'OFF',
	aws_cognito_mfa_types: ['SMS'],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [],
	},
	aws_cognito_verification_mechanisms: ['EMAIL'],
	aws_appsync_graphqlEndpoint: 'https://egf3qypn3jhdbo2wrr52655s74.appsync-api.us-east-1.amazonaws.com/graphql',
	aws_appsync_region: 'us-east-1',
	aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
	aws_appsync_apiKey: 'da2-4nkizhzqdzcohmtbicmeu3eh5a',
	aws_user_files_s3_bucket: 'jtry339112bcac1a547e98c82be0c5ba4f659132721-devjim',
	aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
